### ISSUE TITLE
学习过程中发现的两个小问题

### ISSUE THREAD

**Issue by hulining** [zhangguanzhang/Kubernetes-ansible-ipvs#1]
馆长, 您好,我最近在通过您的 github 学习搭建 k8s 环境,发现您 Kubernetes-ansible-base 这个项目里有两个小问题.
1. 图中两条命令重复了 
https://github.com/zhangguanzhang/Kubernetes-ansible-base/blob/1ba22bcd72e4471a9605915a71bc840aa6243956/tls/tasks/tls.yml#L75
![image](https://user-images.githubusercontent.com/27631386/70704257-a0095280-1d0c-11ea-870a-335754b440df.png)

2. 找不到图中三个模版文件
https://github.com/zhangguanzhang/Kubernetes-ansible-base/blob/1ba22bcd72e4471a9605915a71bc840aa6243956/master/tasks/master.yml#L39

![image](https://user-images.githubusercontent.com/27631386/70704053-3c7f2500-1d0c-11ea-85e1-804291c5f1be.png)

**Comment by hulining** [comment]
@zhangguanzhang

**Comment by zhangguanzhang** [comment]
现在每个版本的master配置文件变化的原因，所以移动到根目录的templates里的，你可以找下，tls这步是重复了的，我有空测试完后发布

**Comment by zhangguanzhang** [comment]
周六我测试下，并发布v1.17版本

**Comment by hulining** [comment]
> 现在每个版本的master配置文件变化的原因，所以移动到根目录的templates里的，你可以找下，tls这步是重复了的，我有空测试完后发布

找到了, 非常感谢~ 
都在这里 [templates](https://github.com/zhangguanzhang/Kubernetes-ansible/tree/master/templates/master)

**Comment by zhangguanzhang** [comment]
更新了`1.17.0`
