### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by pythonTaotao** [zhangguanzhang/Kubernetes-ansible-ipvs#3]
在setup那一步里面reboot那一步操作是否必须呢？如果必须，重启的作用是什么呢，求解答

**Comment by zhangguanzhang** [comment]
内核参数，看我博客，安装步骤是基本相同的，就管理组件的配置文件会变化。有的步骤可以不在乎前后顺序或者耦合在一起否。

 * docker官方的内核检查脚本建议`(RHEL7/CentOS7: User namespaces disabled; add 'user_namespace.enable=1' to boot command line)`,使用下面命令开启
```bash
grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
```

 * 重启加载新内核
```bash
reboot
```
https://zhangguanzhang.github.io/2019/03/03/kubernetes-1-13-4/

**Comment by zhangguanzhang** [comment]
重启是让这个内核参数生效，跟随官方步骤，docker有个检查脚本

**Comment by pythonTaotao** [comment]
看到了，感谢
